### ISSUE TITLE
Appsignal access

### ISSUE THREAD

**Issue by JoschkaSchulz** [rughh/on_ruby#1065]
It would be really cool if @salzig and me are getting Appsignal access. For solving bugs and find things they need to fix to it would be a nice help. Would it be possible to give us the access @phoet?

**Comment by phoet** [comment]
done

**Comment by phoet** [comment]
btw, the appsignal integration is currently free of charge through their opensource program.

**Comment by salzig** [comment]
Thanks @phoet 
But could you check our permissions? Looks like we're having access to the org, but can't see environments? (haven't used app signal in the last 9 years)
![Screenshot 2024-10-17 at 09 43 56](https://github.com/user-attachments/assets/3db0f99a-41da-479d-8d46-6b01e72e2c3b)

**Comment by phoet** [comment]
i changed the team structure a bit and you cant change the invitation, so i have to add you manually.

**Comment by phoet** [comment]
should be good now

**Comment by salzig** [comment]
@phoet thanks!

**Comment by JoschkaSchulz** [comment]
Thanks you, works like a charm :)
