### ISSUE TITLE
github integration

### ISSUE THREAD

**Issue by phoet** [rughh/on_ruby#253]
the ruby usergroup hamburg is doing most of the [planning on github](https://github.com/rughh/planning) nowadays. 

i think it would be useful to have the following optional links on the site

* [x] general link to a planning repo, possibly very visible on the main site
* [x] a github icon/link next to the event title (on the event page)
* [ ] a github icon/link next to a topic that was discussed as a github issue

additionally, we could directly create new issues when someone proposes a topic or copy issues as topic into the app in the admin.

in order to build this we would need

* [x] whitelabel.yml field for the github repo (optional, usergroups might not have it)
* [x] a column on the event for the respective issue (adding it in the admin)
* [x] a column on the topic for the respective issue (adding it in the admin)

**Comment by janz93** [comment]
@phoet I would love to help you on that.
 Maybe something like iftt could also be helpful at the integration between the website and github.
Another thing to think about implementing could be the following: https://github.com/kentcdodds/all-contributors

**Comment by phoet** [comment]
@janz93 i don't know how you would want to connect the website and github though iftt, but feel free to provide a pull-request.

a contributors script can be found here https://github.com/phoet/on_ruby/blob/master/script/generate-humans

**Comment by janz93** [comment]
@phoet thanks I'll take a look at

**Comment by janz93** [comment]
@phoet This might be at the wrong place here but the difference between the contributor script and the idea I showed you with the GitHub link is the following:
It doesn't matter whether you have contributed the to the repro via a git commit or just with a talk about it. Anyway, you have contributed to a repro. I feel especially for new people like myself it's always a bit difficult to get into the open source world and see how you can help on a project.
But even small things as informing do help projects as well.

**Comment by phoet** [comment]
the app is a whitelabel system. the talks for usergroups have nothing to do with.

**Comment by janz93** [comment]
Yes I kind of realized that so nevermind the comment :sweat_smile:

**Comment by janz93** [comment]
@phoet Where would you add the github repo link in the backend?

**Comment by phoet** [comment]
@janz93 see the TODOs
