### ISSUE TITLE
Self-Signup

### ISSUE THREAD

**Issue by skade** [rughh/on_ruby#278]
I'd be heavily interested in a self-signup option for on_ruby.

I investigated that a while ago and - as far as I see - the biggest issue there is the whitelabel method on_ruby uses. Would patches to make this more dynamic be accepted?

**Comment by phoet** [comment]
@skade i've discussed this idea with several people and we always ended up not doing it. that does not mean that i would reject patches, it's more like there are some technical hurdles and communication needs to happen no matter what. so in the past what we did was to guide through the process of onboarding and usually that worked pretty well.

**Comment by phoet** [comment]
@skade if you have a specific usergroup in mind, let's walk through with that example and have a look at what can be done to lower the hurdles.

I'm also completely open to renaiming onruby, moving it to a different organization to make it more transportable.

**Comment by phoet** [comment]
see also https://github.com/phoet/on_ruby/issues/206
