### ISSUE TITLE
Gather ideas for sending emails to all people of one user group

### ISSUE THREAD

**Issue by mediafinger** [rughh/on_ruby#624]
First the ticket to separate user data by usergroup https://github.com/phoet/on_ruby/issues/622 has to be solved.

Then when every usergroup has their own users, it would be great to have functionality to send all users that entered their email address emails (over a service like Sendgrid).

Once this works, sending emails to all people appointed to an event should be easy to implement.

**Comment by phoet** [comment]
Not sending emails to users is kind of a feature right now 😀

If you really want to send reminders, that should be pretty straight forward through whats already there.

**Comment by mediafinger** [comment]
Do you mean sending an email to the googlegroup? While we do have one, it is basically unused and most people wouldn't see those messages.

Sending messages to the group (better: one to each user) is the 2nd most missed feature for us when moving away from meetup. (Number 1 is discoverability, but that will be harder to "implement".)

**Comment by phoet** [comment]
I mean user based reminders. Those do intentionality not exist, because they are perceived as annoying on Meetup.

**Comment by phoet** [comment]
Mailers are already setup and can be used with sendgrid for whatever purpose.

**Comment by mediafinger** [comment]
Ah, good to know. Guess it is worth to study the  current implementation and check how it can be generalized or made configurable.
