### ISSUE TITLE
Map View On Event Isn't Going To The Right Location

### ISSUE THREAD

**Issue by alterisian** [rughh/on_ruby#635]
The Google maps external link goes to the right location, but the displayed map does not. 

Example: https://andalucia.onruby.eu/events/jet-scaling-ruby-web-apps-573

#bug

**Comment by phoet** [comment]
hi @alterisian this is not really a bug, as it is missing data. maybe there was an issue with geo-coding when you created the event location:

```
"id":280,...,"lat":null,"long":null,
```

i removed the `oficina 406` for now and it looks like this fixes the geo-coding.

there is no field to store such information, but it might make sense to give more advise on how to actually get there.

**Comment by alterisian** [comment]
Maybe something around flashing up geocoding errors in the workflow for adding an event is the way to go?

**Comment by phoet** [comment]
@alterisian will have a look at how this can be improved. right now, i think you dont even see the geocoding anywhere in the admin...

**Comment by alterisian** [comment]
cool. happy to also help and look into it. Just didn't have time when running an event.
