### ISSUE TITLE
Advertise how to host the meetup more publicly

### ISSUE THREAD

**Issue by janz93** [rughh/on_ruby#651]
When someone creates an event without a location it not really clear that a location is needed.
<img width="1352" alt="grafik" src="https://user-images.githubusercontent.com/5300559/71850036-ae604980-30d3-11ea-89b1-8812bcc8c708.png">

Also, there is no it is not really advertised on how someone can host the meetup.
You only have a list of all locations where the usergroup has already been
e.g. https://hamburg.onruby.de/locations

With the link https://hamburg.onruby.de/locations/none you will come to page where it is explained how to become a host.

This means all the pieces of information are already there it is just a matter of the UI

**Comment by phoet** [comment]
the basic idea was that you do not create an event until you actually HAVE a venue 😄 

but yeah, it has caused some confusion, that you can create events without a location. some organizers do it for the purpose of announcing talks etc upfront.

so if you would want to work on this, that would be great!

**Comment by janz93** [comment]
Haha I see 🙈 
I personally also like it to announce talks for a meetup upfront.
Plus it also shows, that the meetup will acctually take place.

I will try to come up with a design idea 🤞 👨‍🎨
